### ISSUE TITLE
ADD_TO_SELECTION_SEMI_TRANSIENT flag doesn't exist

### ISSUE THREAD

**Issue by jwortmann** [jfcherng-sublime/ST-API-stubs#11]
The following flag in the description for `Window.open_file` doesn't exist and should be removed:
https://github.com/jfcherng-sublime/ST-API-stubs/blob/26cad735696ee62e2935c72a679299787e8fcc59/typings/sublime.pyi#L710-L711

**Comment by jfcherng** [comment]
Confirmed in ST 4096's changelog. Thanks. Fixed in 5643d4200485f029dce12d84384161731efba07c.

```
API: Backwards Compatibility Break: sublime.ADD_TO_SELECTION_SEMI_TRANSIENT was removed, should use sublime.ADD_TO_SELECTION | sublime.SEMI_TRANSIENT in place
```
