### ISSUE TITLE
Can View.window() really return None?

### ISSUE THREAD

**Issue by jwortmann** [jfcherng-sublime/ST-API-stubs#3]
I get a lot of type errors from pyright when using `sublime.View.window()`, because in the stub file its type is specified as `Optional[Window]`. The API docs have the return value as `Window`, and don't mention anything that it could return `None`. Is it actually somehow possible that it returns `None` and do I have to use something like
```python
if window:
    ...
```
everywhere in my code, or is the type annotation in the stub file incorrect?

I guess the same applies to `Sheet.window()`.

Btw. thanks for this repository!

**Comment by jfcherng** [comment]
According to https://www.sublimetext.com/docs/api_reference.html#sublime.View , `view.window()` never returns `None`. And `Sheet.window()` may return `None`.

Not sure whether there is any typo in the docs or not though.

**Comment by jwortmann** [comment]
Ah you're right,
> May be `None` if the sheet has been closed.

I just tried with a little test plugin and the same applies to views too. So the type here seems to be correct and the description in the docs is just missing this detail.

```python
import sublime
import sublime_plugin

class FooCommand(sublime_plugin.TextCommand):
    def run(self, edit):
        v = self.view
        print(v)
        v.close()
        print(v)
        print(v.window())
```

```
>>> view.run_command("foo")
View(17)
View(17)
None
```
