### ISSUE TITLE
ExtractVariablesDict is incompatible with Dict[str, str]

### ISSUE THREAD

**Issue by jwortmann** [jfcherng-sublime/ST-API-stubs#8]
Using LSP-pyright.

```python
import sublime
import sublime_plugin


class MyCommand(sublime_plugin.WindowCommand):
    def run(self):
        variables = self.window.extract_variables()
        print(sublime.expand_variables("Platform: $platform", variables))
```

According to the docs, `sublime.Window.extract_variables()` returns `Dict[str, str]`, and
> This `dict` is suitable for use with [expand_variables()](https://www.sublimetext.com/docs/api_reference.html#sublime.expand_variables).

But pyright shows the following error:

![Unbenannt](https://user-images.githubusercontent.com/6579999/171954130-e308a18b-246c-4d0f-96b3-3971c0d0f2a5.png)

Is it a bug in pyright (i.e. maybe pyright can't see that all values in the TypedDict are `str`?), or can it be fixed in the type stubs?

**Comment by jfcherng** [comment]
I changed the return type from `Dict[str, str]` to `ExtractVariablesDict` to benefit from having autocompletion for keys. But it also gives wanted side effects...

**Comment by jfcherng** [comment]
Reverted in 7769463. Will be in the next release of LSP-pyright.
